development:
  host: localhost
  port: 389
  dn: dc=company,dc=com
  username: ittest01@company.com
  password: Abc$1234
production:
  host: localhost
  port: 389
  dn: dc=company,dc=com
  username: ittest01@company.com
  password: Abc$1234
test:
  host: localhost
  port: 389
  dn: dc=company,dc=com
  username: ittest01@company.com
  password: Abc$1234